# -*- coding: utf-8 -*-
"""PART 3 - Basic Branching, Looping & Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13VgtPE3C8719Z0_tIeIRkZatFxZpCtH9

Problem 1 - Konversi Nilai
"""

nilai = int(input('masukan nilai'))

if nilai <= 34:
  print('Nilai D')
if nilai <= 49:
  print('Nilai C')
elif nilai <= 64:
  print('Nilai B')
elif nilai <= 79:
  print('Nilai B+')
else:
  print('Nilai A')

"""Problem 2.1 - Faktor Bilangan

"""

def faktor(bilangan):
    faktor = []
    for i in range(1, bilangan + 1):
        if bilangan % i == 0:
            faktor.append(i)

    for faktor_bilangan in faktor:
        print(faktor_bilangan)

bilangan = int(input("Masukkan bilangan: "))
faktor(bilangan)

"""Problem 2.2 - Faktor Bilangan"""

def faktor(bilangan):
    faktor = []
    for i in range(1, bilangan + 1):
        if bilangan % i == 0:
            faktor.append(i)

    for faktor_bilangan in faktor:
        print(faktor_bilangan)

bilangan = int(input("Masukkan bilangan: "))
faktor(bilangan)

"""Problem 3 - Bilangan Prima"""

def bilangan_prima(bilangan):
    if bilangan < 2:
        return False

    for i in range(2, int(bilangan ** 0.5) + 1):
        if bilangan % i == 0:
            return False

    return True

bilangan = int(input("Masukkan bilangan: "))
if bilangan_prima(bilangan):
    print("true")
else:
    print("false")

"""Problem 4 - Palindrome"""

def palindrom(string):
    return string == string[::-1]

string = input("Masukkan kata: ")
if palindrom(string):
    print("true")
else:
    print("false")

"""Problem 5 - Exponentiation"""

def hitung_pangkat(x, n):
    hasil = 1
    for _ in range(n):
        hasil *= x
    return hasil

x = int(input("Masukkan nilai x: "))
n = int(input("Masukkan nilai n: "))
pangkat = hitung_pangkat(x, n)
print(pangkat)

"""Fu"""

def bilangan_prima(bilangan):
    if bilangan < 2:
        return False

    for i in range(2, int(bilangan ** 0.5) + 1):
        if bilangan % i == 0:
            return False
    return True

def full_prima(bilangan):
    for digit in str(bilangan):
        if not bilangan_prima(int(digit)):
            return False
    return True

bilangan = int(input("Masukkan bilangan: "))
if full_prima(bilangan):
    print("Ya")
else:
    print("Tidak")